In [24]:
import pandas as pd
import json
import requests
import copy
import matplotlib.pyplot as plt
import xgboost as xgb
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import KFold
from sklearn import model_selection, preprocessing, metrics
import seaborn as sns
import  estateFunction

ImportError: No module named 'sklearn.model_selection'

In [9]:
data2018=pd.read_csv('dataAfterPreprocess/data2018') 
data2017=pd.read_csv('dataAfterPreprocess/data2017')
data2016=pd.read_csv('dataAfterPreprocess/data2016') 
data2015=pd.read_csv('dataAfterPreprocess/data2015') 
data2014=pd.read_csv('dataAfterPreprocess/data2014') 
data2013=pd.read_csv('dataAfterPreprocess/data2013') 
data2012=pd.read_csv('dataAfterPreprocess/data2012') 
data2011=pd.read_csv('dataAfterPreprocess/data2011') 
data2010=pd.read_csv('dataAfterPreprocess/data2010')

In [10]:
###merge all data
train=pd.concat([data2018,data2017,data2016,data2015,data2014,data2013,data2012,data2011,data2010],axis=0)
train=train.reset_index()
del train['index']
train.shape

(710731, 16)

In [11]:
###checikng the null data
train.isnull().sum()

시군구             0
번지              0
본번              0
부번              0
단지명             0
전용면적(㎡)         0
계약년월            0
거래금액(만원)        0
층               0
건축년도            0
도로명          1345
latitude        0
longitude       0
big             0
small           0
month           0
dtype: int64

In [12]:
###결측치 drop함
train=train.drop(train.index[train['도로명'].isnull()],0)

In [13]:
train.isnull().sum().sum(),len(train)

(0, 709386)

In [ ]:
###이상치를제거하자

In [14]:
###280이상은 제거하자.
train.sort_values(["전용면적(㎡)"],ascending=False)[:20]

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,거래금액(만원),층,건축년도,도로명,latitude,longitude,big,small,month
3468,서울특별시 강남구 도곡동,193-1,193,1,힐데스하임빌라,424.320,201604,498000.0,10,1998,남부순환로377길,37.488126,127.045025,강남구,도곡동,4
266300,서울특별시 서초구 서초동,1518-2,1518,2,월드빌라트,395.060,201809,290000.0,10,1996,명달로16길,37.485489,127.005450,서초구,서초동,9
506741,서울특별시 강남구 청담동,89-12,89,12,청담동마크노빌,325.390,201302,420000.0,6,2008,도산대로59길,37.525378,127.042161,강남구,청담동,2
405833,서울특별시 용산구 이촌동,302-69,302,69,정우,317.360,201509,118000.0,7,1972,이촌로54길,37.520833,126.967177,용산구,이촌동,9
287806,서울특별시 용산구 이촌동,302-69,302,69,정우,317.360,201810,157000.0,5,1972,이촌로54길,37.520833,126.967177,용산구,이촌동,10
405832,서울특별시 용산구 이촌동,302-69,302,69,정우,317.360,201504,85000.0,2,1972,이촌로54길,37.520833,126.967177,용산구,이촌동,4
543742,서울특별시 서초구 반포동,612-33,612,33,펠리체,283.760,201302,180000.0,5,2007,동광로27길,37.496575,126.994165,서초구,반포동,2
264798,서울특별시 서초구 반포동,612-33,612,33,펠리체,283.760,201808,185000.0,5,2007,동광로27길,37.496575,126.994165,서초구,반포동,8
507711,서울특별시 강동구 길동,351-2,351,2,신세대빌라트,283.000,201312,63000.0,9,1999,천중로,37.540564,127.144661,강동구,길동,12
106928,서울특별시 중구 흥인동,13-1,13,1,청계천 두산위브더제니스,273.967,201607,228977.0,28,2014,다산로46길,37.566863,127.017110,중구,흥인동,7
106940,서울특별시 중구 흥인동,13-1,13,1,청계천 두산위브더제니스,273.967,201608,152074.0,28,2014,다산로46길,37.566863,127.017110,중구,흥인동,8
373213,서울특별시 서초구 서초동,1496-24,1496,24,트라움하우스3,273.860,201501,490000.0,5,2002,명달로,37.486188,127.002931,서초구,서초동,1
176523,서울특별시 서초구 서초동,1496-24,1496,24,트라움하우스3,273.860,201707,480000.0,4,2002,명달로,37.486188,127.002931,서초구,서초동,7
371106,서울특별시 서초구 방배동,1-21,1,21,방배롯데캐슬OSCAR,273.540,201511,265000.0,1,2006,동광로27길,37.494586,126.994382,서초구,방배동,11
117230,서울특별시 강남구 청담동,121-14,121,14,청담8차상지리츠빌,273.450,201702,278000.0,4,2003,도산대로83길,37.525707,127.048573,강남구,청담동,2
117231,서울특별시 강남구 청담동,121-14,121,14,청담8차상지리츠빌,273.450,201712,310000.0,4,2003,도산대로83길,37.525707,127.048573,강남구,청담동,12
174265,서울특별시 서초구 방배동,1-43,1,43,라파예트,273.370,201707,140000.0,5,2001,사평대로6길,37.494726,126.993206,서초구,방배동,7
264251,서울특별시 서초구 반포동,110-6,110,6,그랑빌,273.310,201801,220000.0,8,2001,사평대로14길,37.497227,126.994680,서초구,반포동,1
543008,서울특별시 서초구 반포동,110-6,110,6,그랑빌,273.310,201301,205000.0,8,2001,사평대로14길,37.497227,126.994680,서초구,반포동,1
67914,서울특별시 서초구 방배동,804-5,804,5,레베빌2,273.130,201609,263000.0,6,2004,서초대로33길,37.492949,126.994667,서초구,방배동,9

In [15]:
##삭제됨
train=train.drop(train.index[train["전용면적(㎡)"]>280],0)

In [ ]:
###거래금액은 이상치로 판단이 잘안됨.
###1.3개월에 2번 거래된거 
###2.전판매가 5배이상 제거하자

In [16]:
###단지명,층,전용면적까지 같으면 같은건물로 보고
###계약년월 순대로 정렬함
train=train.sort_values(["단지명","층","전용면적(㎡)","계약년월"])

In [18]:
train=train.reset_index()
del train['index']

In [19]:
#3개월에 2번 거래된것 삭제
train=estateFunction.deleteOutlier(train)

NameError: name 'estateFunction' is not defined